[package]
name = "fastly-static-site"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.70"
mime_guess = "2.0.4"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "2.0.15"
walkdir = "2.3.3"
wildmatch = "2.1.1"
