[package]
name = "fastly-static-site"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.69"
mime_guess = "2.0.4"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "1.0.107"
walkdir = "2.3.2"
wildmatch = "2.1.1"
