[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
once_cell = "1.18.0"
wasm-compose = "0.4.2"
wasmparser = "0.112.0"
wat = "1.0.71"
wit-component = "0.14.0"
cargo-component-bindings = { git = "https://github.com/bytecodealliance/cargo-component" }

[package.metadata.component]

[package.metadata.component.target]
path = "world.wit"
