[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.66"
once_cell = "1.16.0"
wasm-compose = "0.2.1"
wasmparser = "0.95.0"
wat = "1.0.52"
wit-component = "0.3.2"

[package.metadata.component]
direct-export = "interface"

[package.metadata.component.exports]
interface = "interface.wit"
