[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
once_cell = "1.18.0"
wasm-compose = "0.3.0"
wasmparser = "0.108.0"
wat = "1.0.67"
wit-component = "0.12.0"

[package.metadata.component]

[package.metadata.component.target]
path = "world.wit"
