[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
once_cell = "1.17.1"
wasm-compose = { git = "https://github.com/bytecodealliance/wasm-tools" }
wasmparser = { git = "https://github.com/bytecodealliance/wasm-tools" }
wat = { git = "https://github.com/bytecodealliance/wasm-tools" }
wit-component = { git = "https://github.com/bytecodealliance/wasm-tools" }

[package.metadata.component]
target = { path = "world.wit" }
