[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
once_cell = "1.17.2"
wasm-compose = "0.2.17"
wasmparser = "0.107.0"
wat = "1.0.66"
wit-component = "0.11.0"

[package.metadata.component]

[package.metadata.component.target]
path = "world.wit"
