[package]
name = "graph"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.70"
once_cell = "1.17.1"
wasm-compose = "0.2.13"
wasmparser = "0.104.0"
wat = "1.0.63"
wit-component = "0.8.2"

[package.metadata.component]
target = { path = "world.wit" }
